const { test } = require('@kmamal/testing')
const { merge } = require('./merge')

test('object.merge', (t) => {
	t.equal(merge({}, {}), {})
	t.equal(merge({ a: 1 }, {}), { a: 1 })
	t.equal(merge({ a: 1, b: 2 }, {}), { a: 1, b: 2 })
	t.equal(merge({ a: 1, b: 2 }, { a: 3 }), { a: 3, b: 2 })
	t.equal(merge({ a: 1, b: 2 }, { a: null }), { a: null, b: 2 })
	t.equal(merge({ a: 1, b: 2 }, { c: 3 }), { a: 1, b: 2, c: 3 })
	t.equal(merge({ a: 1, b: 2 }, { a: {} }), { a: {}, b: 2 })
	t.equal(merge({ a: 1, b: 2 }, { a: [] }), { a: [], b: 2 })
	t.equal(merge({ a: {}, b: 2 }, { a: [] }), { a: [], b: 2 })
	t.equal(merge({ a: {}, b: 2 }, { a: {} }), { a: {}, b: 2 })
	t.equal(merge({ a: {}, b: 2 }, { a: { c: 3 } }), { a: { c: 3 }, b: 2 })
	t.equal(merge({ a: { c: 3 }, b: 2 }, { a: { c: 4 } }), { a: { c: 4 }, b: 2 })
})

test('object.merge$$$', (t) => {
	t.equal(merge.$$$({}, {}), {})
	t.equal(merge.$$$({ a: 1 }, {}), { a: 1 })
	t.equal(merge.$$$({ a: 1, b: 2 }, {}), { a: 1, b: 2 })
	t.equal(merge.$$$({ a: 1, b: 2 }, { a: 3 }), { a: 3, b: 2 })
	t.equal(merge.$$$({ a: 1, b: 2 }, { a: null }), { a: null, b: 2 })
	t.equal(merge.$$$({ a: 1, b: 2 }, { c: 3 }), { a: 1, b: 2, c: 3 })
	t.equal(merge.$$$({ a: 1, b: 2 }, { a: {} }), { a: {}, b: 2 })
	t.equal(merge.$$$({ a: 1, b: 2 }, { a: [] }), { a: [], b: 2 })
	t.equal(merge.$$$({ a: {}, b: 2 }, { a: [] }), { a: [], b: 2 })
	t.equal(merge.$$$({ a: {}, b: 2 }, { a: {} }), { a: {}, b: 2 })
	t.equal(merge.$$$({ a: {}, b: 2 }, { a: { c: 3 } }), { a: { c: 3 }, b: 2 })
	t.equal(merge.$$$({ a: { c: 3 }, b: 2 }, { a: { c: 4 } }), { a: { c: 4 }, b: 2 })
})
