// THIS FILE IS AUTOGENERATED

module.exports.array2d = {}
module.exports.array = {}
module.exports.search = {}
module.exports.heap = {}
module.exports.tree = {}
module.exports.tree.binary = {}
module.exports.tree.quaternary = {}
module.exports.tree.octonary = {}
module.exports.ieeeFloat = {}
module.exports.ieeeFloat.single = {}
module.exports.ieeeFloat.double = {}
module.exports.modular = {}
module.exports.object = {}
module.exports.sets = {}

const array2dClass = require('./array/2d/class.js')
module.exports.array2d.Array2d = array2dClass.Array2d

const array2dClone = require('./array/2d/clone.js')
module.exports.array2d.clone = array2dClone.clone

const array2dCombine = require('./array/2d/combine.js')
module.exports.array2d.__combine = array2dCombine.__combine
module.exports.array2d.combine = array2dCombine.combine

const array2dCopy = require('./array/2d/copy.js')
module.exports.array2d.__copy = array2dCopy.__copy
module.exports.array2d.copy = array2dCopy.copy

const array2dEndIndex = require('./array/2d/end-index.js')
module.exports.array2d.endIndex = array2dEndIndex.endIndex

const array2dEndPoint = require('./array/2d/end-point.js')
module.exports.array2d.endPoint = array2dEndPoint.endPoint

const array2dFill = require('./array/2d/fill.js')
module.exports.array2d.__fill = array2dFill.__fill
module.exports.array2d.fill = array2dFill.fill

const array2dFromFactory = require('./array/2d/from-factory.js')
module.exports.array2d.fromFactory = array2dFromFactory.fromFactory

const array2dSlice = require('./array/2d/slice.js')
module.exports.array2d.slice = array2dSlice.slice

const array2dStartIndex = require('./array/2d/start-index.js')
module.exports.array2d.startIndex = array2dStartIndex.startIndex

const array2dStartPoint = require('./array/2d/start-point.js')
module.exports.array2d.startPoint = array2dStartPoint.startPoint

const arrayChunk = require('./array/chunk.js')
module.exports.__chunk = arrayChunk.__chunk
module.exports.chunk = arrayChunk.chunk

const arrayClone = require('./array/clone.js')
module.exports.clone = arrayClone.clone

const arrayCombinatoricsCombinations = require('./array/combinatorics/combinations.js')
module.exports.combinations = arrayCombinatoricsCombinations.combinations

const arrayCombinatoricsPermutations = require('./array/combinatorics/permutations.js')
module.exports.permutations = arrayCombinatoricsPermutations.permutations

const arrayCombinatoricsProduct = require('./array/combinatorics/product.js')
module.exports.product = arrayCombinatoricsProduct.product

const arrayCombine = require('./array/combine.js')
module.exports.__combine = arrayCombine.__combine
module.exports.combine = arrayCombine.combine

const arrayComm = require('./array/comm.js')
module.exports.__comm = arrayComm.__comm
module.exports.commWith = arrayComm.commWith
module.exports.commBy = arrayComm.commBy
module.exports.commByPure = arrayComm.commByPure
module.exports.comm = arrayComm.comm

const arrayCompactMap = require('./array/compact-map.js')
module.exports.__compactMap = arrayCompactMap.__compactMap
module.exports.compactMap = arrayCompactMap.compactMap

const arrayCompact = require('./array/compact.js')
module.exports.compact = arrayCompact.compact

const arrayConcat = require('./array/concat.js')
module.exports.__concat = arrayConcat.__concat
module.exports.concat = arrayConcat.concat

const arrayCopy = require('./array/copy.js')
module.exports.__copy = arrayCopy.__copy
module.exports.__copyRight = arrayCopy.__copyRight
module.exports.__copyInplace = arrayCopy.__copyInplace
module.exports.copy = arrayCopy.copy

const arrayCount = require('./array/count.js')
module.exports.__count = arrayCount.__count
module.exports.countBy = arrayCount.countBy
module.exports.count = arrayCount.count

const arrayCycle = require('./array/cycle.js')
module.exports.__cycle = arrayCycle.__cycle
module.exports.cycle = arrayCycle.cycle

const arrayDifference = require('./array/difference.js')
module.exports.__difference = arrayDifference.__difference
module.exports.differenceWith = arrayDifference.differenceWith
module.exports.differenceBy = arrayDifference.differenceBy
module.exports.differenceByPure = arrayDifference.differenceByPure
module.exports.difference = arrayDifference.difference
module.exports.differenceWithSorted = arrayDifference.differenceWithSorted
module.exports.differenceBySorted = arrayDifference.differenceBySorted
module.exports.differenceByPureSorted = arrayDifference.differenceByPureSorted
module.exports.differenceSorted = arrayDifference.differenceSorted

const arrayEndIndex = require('./array/end-index.js')
module.exports.endIndex = arrayEndIndex.endIndex

const arrayEvery = require('./array/every.js')
module.exports.__every = arrayEvery.__every
module.exports.every = arrayEvery.every

const arrayFill = require('./array/fill.js')
module.exports.__fill = arrayFill.__fill
module.exports.__fillWith = arrayFill.__fillWith
module.exports.fill = arrayFill.fill
module.exports.fillWith = arrayFill.fillWith

const arrayFilter = require('./array/filter.js')
module.exports.__filter = arrayFilter.__filter
module.exports.filter = arrayFilter.filter

const arrayFind = require('./array/find.js')
module.exports.findIndex = arrayFind.findIndex
module.exports.findIndexRight = arrayFind.findIndexRight
module.exports.find = arrayFind.find
module.exports.findRight = arrayFind.findRight

const arrayFirst = require('./array/first.js')
module.exports.first = arrayFirst.first

const arrayFlatMap = require('./array/flat-map.js')
module.exports.__flatMap = arrayFlatMap.__flatMap
module.exports.flatMap = arrayFlatMap.flatMap

const arrayFlat = require('./array/flat.js')
module.exports.flat = arrayFlat.flat

const arrayForEach = require('./array/for-each.js')
module.exports.forEach = arrayForEach.forEach

const arrayGroupBy = require('./array/group-by.js')
module.exports.groupBy = arrayGroupBy.groupBy

const arrayHeapAdd = require('./array/heap/add.js')
module.exports.heap.__add = arrayHeapAdd.__add
module.exports.heap.addWith = arrayHeapAdd.addWith
module.exports.heap.addBy = arrayHeapAdd.addBy
module.exports.heap.add = arrayHeapAdd.add

const arrayHeapBubbleDown = require('./array/heap/bubble-down.js')
module.exports.heap.__bubbleDown = arrayHeapBubbleDown.__bubbleDown
module.exports.heap.bubbleDownWith = arrayHeapBubbleDown.bubbleDownWith
module.exports.heap.bubbleDownBy = arrayHeapBubbleDown.bubbleDownBy
module.exports.heap.bubbleDown = arrayHeapBubbleDown.bubbleDown

const arrayHeapBubbleUp = require('./array/heap/bubble-up.js')
module.exports.heap.__bubbleUp = arrayHeapBubbleUp.__bubbleUp
module.exports.heap.bubbleUpWith = arrayHeapBubbleUp.bubbleUpWith
module.exports.heap.bubbleUpBy = arrayHeapBubbleUp.bubbleUpBy
module.exports.heap.bubbleUp = arrayHeapBubbleUp.bubbleUp

const arrayHeapHeapify = require('./array/heap/heapify.js')
module.exports.heap.__heapify = arrayHeapHeapify.__heapify
module.exports.heap.heapifyWith = arrayHeapHeapify.heapifyWith
module.exports.heap.heapifyBy = arrayHeapHeapify.heapifyBy
module.exports.heap.heapify = arrayHeapHeapify.heapify

const arrayHeapPop = require('./array/heap/pop.js')
module.exports.heap.__pop = arrayHeapPop.__pop
module.exports.heap.popWith = arrayHeapPop.popWith
module.exports.heap.popBy = arrayHeapPop.popBy
module.exports.heap.pop = arrayHeapPop.pop

const arrayIncludes = require('./array/includes.js')
module.exports.__includes = arrayIncludes.__includes
module.exports.__includesSorted = arrayIncludes.__includesSorted
module.exports.includesWith = arrayIncludes.includesWith
module.exports.includesBy = arrayIncludes.includesBy
module.exports.includesByPure = arrayIncludes.includesByPure
module.exports.includes = arrayIncludes.includes
module.exports.includesWithSorted = arrayIncludes.includesWithSorted
module.exports.includesBySorted = arrayIncludes.includesBySorted
module.exports.includesByPureSorted = arrayIncludes.includesByPureSorted
module.exports.includesSorted = arrayIncludes.includesSorted

const arrayIndexOf = require('./array/index-of.js')
module.exports.__indexOf = arrayIndexOf.__indexOf
module.exports.__indexOfRight = arrayIndexOf.__indexOfRight
module.exports.__indexOfSorted = arrayIndexOf.__indexOfSorted
module.exports.__indexOfSortedRight = arrayIndexOf.__indexOfSortedRight
module.exports.indexOfWith = arrayIndexOf.indexOfWith
module.exports.indexOfWithRight = arrayIndexOf.indexOfWithRight
module.exports.indexOfBy = arrayIndexOf.indexOfBy
module.exports.indexOfByRight = arrayIndexOf.indexOfByRight
module.exports.indexOfByPure = arrayIndexOf.indexOfByPure
module.exports.indexOfByPureRight = arrayIndexOf.indexOfByPureRight
module.exports.indexOf = arrayIndexOf.indexOf
module.exports.indexOfRight = arrayIndexOf.indexOfRight
module.exports.indexOfWithSorted = arrayIndexOf.indexOfWithSorted
module.exports.indexOfWithSortedRight = arrayIndexOf.indexOfWithSortedRight
module.exports.indexOfBySorted = arrayIndexOf.indexOfBySorted
module.exports.indexOfBySortedRight = arrayIndexOf.indexOfBySortedRight
module.exports.indexOfByPureSorted = arrayIndexOf.indexOfByPureSorted
module.exports.indexOfByPureSortedRight = arrayIndexOf.indexOfByPureSortedRight
module.exports.indexOfSorted = arrayIndexOf.indexOfSorted
module.exports.indexOfSortedRight = arrayIndexOf.indexOfSortedRight

const arrayInterpose = require('./array/interpose.js')
module.exports.__interposeLeft = arrayInterpose.__interposeLeft
module.exports.__interposeRight = arrayInterpose.__interposeRight
module.exports.__interpose = arrayInterpose.__interpose
module.exports.interpose = arrayInterpose.interpose

const arrayIntersection = require('./array/intersection.js')
module.exports.__intersection = arrayIntersection.__intersection
module.exports.intersectionWith = arrayIntersection.intersectionWith
module.exports.intersectionBy = arrayIntersection.intersectionBy
module.exports.intersectionByPure = arrayIntersection.intersectionByPure
module.exports.intersection = arrayIntersection.intersection
module.exports.intersectionWithSorted = arrayIntersection.intersectionWithSorted
module.exports.intersectionBySorted = arrayIntersection.intersectionBySorted
module.exports.intersectionByPureSorted = arrayIntersection.intersectionByPureSorted
module.exports.intersectionSorted = arrayIntersection.intersectionSorted

const arrayIsSorted = require('./array/is-sorted.js')
module.exports.__isSorted = arrayIsSorted.__isSorted
module.exports.isSortedWith = arrayIsSorted.isSortedWith
module.exports.isSortedBy = arrayIsSorted.isSortedBy
module.exports.isSortedByPure = arrayIsSorted.isSortedByPure
module.exports.isSorted = arrayIsSorted.isSorted

const arrayJoin = require('./array/join.js')
module.exports.array.join = arrayJoin.join

const arrayLast = require('./array/last.js')
module.exports.last = arrayLast.last

const arrayMap = require('./array/map.js')
module.exports.__map = arrayMap.__map
module.exports.map = arrayMap.map

const arrayMax = require('./array/max.js')
module.exports.__max = arrayMax.__max
module.exports.maxIndexBy = arrayMax.maxIndexBy
module.exports.maxIndex = arrayMax.maxIndex
module.exports.maxBy = arrayMax.maxBy
module.exports.max = arrayMax.max

const arrayMerge = require('./array/merge.js')
module.exports.__merge = arrayMerge.__merge
module.exports.__mergeRight = arrayMerge.__mergeRight
module.exports.__mergeInplace = arrayMerge.__mergeInplace
module.exports.mergeWith = arrayMerge.mergeWith
module.exports.mergeBy = arrayMerge.mergeBy
module.exports.mergeByPure = arrayMerge.mergeByPure
module.exports.merge = arrayMerge.merge

const arrayMin = require('./array/min.js')
module.exports.__min = arrayMin.__min
module.exports.minIndexBy = arrayMin.minIndexBy
module.exports.minIndex = arrayMin.minIndex
module.exports.minBy = arrayMin.minBy
module.exports.min = arrayMin.min

const arrayNth = require('./array/nth.js')
module.exports.nth = arrayNth.nth

const arrayPrefixSums = require('./array/prefix-sums.js')
module.exports.prefixSumsBy = arrayPrefixSums.prefixSumsBy
module.exports.prefixSums = arrayPrefixSums.prefixSums

const arrayProxy = require('./array/proxy.js')
module.exports.makeProxy = arrayProxy.makeProxy

const arrayReduce = require('./array/reduce.js')
module.exports.__reduce = arrayReduce.__reduce
module.exports.__reduceRight = arrayReduce.__reduceRight
module.exports.reduce = arrayReduce.reduce
module.exports.reduceRight = arrayReduce.reduceRight

const arrayRepeat = require('./array/repeat.js')
module.exports.array.repeat = arrayRepeat.repeat

const arrayReverse = require('./array/reverse.js')
module.exports.__reverse = arrayReverse.__reverse
module.exports.reverse = arrayReverse.reverse

const arrayRotate = require('./array/rotate.js')
module.exports.__rotate = arrayRotate.__rotate
module.exports.__rotateInplace = arrayRotate.__rotateInplace
module.exports.rotate = arrayRotate.rotate

const arrayScan = require('./array/scan.js')
module.exports.__scan = arrayScan.__scan
module.exports.__scanRight = arrayScan.__scanRight
module.exports.scan = arrayScan.scan
module.exports.scanRight = arrayScan.scanRight

const arraySearchBinary = require('./array/search/binary.js')
module.exports.search.__binarySearch = arraySearchBinary.__binarySearch
module.exports.search.__binarySearchLeft = arraySearchBinary.__binarySearchLeft
module.exports.search.__binarySearchRight = arraySearchBinary.__binarySearchRight
module.exports.search.binarySearchWith = arraySearchBinary.binarySearchWith
module.exports.search.binarySearchLeftWith = arraySearchBinary.binarySearchLeftWith
module.exports.search.binarySearchRightWith = arraySearchBinary.binarySearchRightWith
module.exports.search.binarySearchBy = arraySearchBinary.binarySearchBy
module.exports.search.binarySearchLeftBy = arraySearchBinary.binarySearchLeftBy
module.exports.search.binarySearchRightBy = arraySearchBinary.binarySearchRightBy
module.exports.search.binarySearchByPure = arraySearchBinary.binarySearchByPure
module.exports.search.binarySearchLeftByPure = arraySearchBinary.binarySearchLeftByPure
module.exports.search.binarySearchRightByPure = arraySearchBinary.binarySearchRightByPure
module.exports.search.binarySearch = arraySearchBinary.binarySearch
module.exports.search.binarySearchLeft = arraySearchBinary.binarySearchLeft
module.exports.search.binarySearchRight = arraySearchBinary.binarySearchRight

const arraySearchExponential = require('./array/search/exponential.js')
module.exports.search.__initExponentialSearch = arraySearchExponential.__initExponentialSearch
module.exports.search.__expandExponentialSearch = arraySearchExponential.__expandExponentialSearch
module.exports.search.__contractExponentialSearch = arraySearchExponential.__contractExponentialSearch
module.exports.search.__exponentialSearch = arraySearchExponential.__exponentialSearch
module.exports.search.__exponentialSearchLeft = arraySearchExponential.__exponentialSearchLeft
module.exports.search.__exponentialSearchRight = arraySearchExponential.__exponentialSearchRight
module.exports.search.exponentialSearchWith = arraySearchExponential.exponentialSearchWith
module.exports.search.exponentialSearchLeftWith = arraySearchExponential.exponentialSearchLeftWith
module.exports.search.exponentialSearchRightWith = arraySearchExponential.exponentialSearchRightWith
module.exports.search.exponentialSearchBy = arraySearchExponential.exponentialSearchBy
module.exports.search.exponentialSearchLeftBy = arraySearchExponential.exponentialSearchLeftBy
module.exports.search.exponentialSearchRightBy = arraySearchExponential.exponentialSearchRightBy
module.exports.search.exponentialSearchByPure = arraySearchExponential.exponentialSearchByPure
module.exports.search.exponentialSearchLeftByPure = arraySearchExponential.exponentialSearchLeftByPure
module.exports.search.exponentialSearchRightByPure = arraySearchExponential.exponentialSearchRightByPure
module.exports.search.exponentialSearch = arraySearchExponential.exponentialSearch
module.exports.search.exponentialSearchLeft = arraySearchExponential.exponentialSearchLeft
module.exports.search.exponentialSearchRight = arraySearchExponential.exponentialSearchRight

const arraySearchInterpolation = require('./array/search/interpolation.js')
module.exports.search.__interpolationSearch = arraySearchInterpolation.__interpolationSearch
module.exports.search.__interpolationSearchLeft = arraySearchInterpolation.__interpolationSearchLeft
module.exports.search.__interpolationSearchRight = arraySearchInterpolation.__interpolationSearchRight
module.exports.search.interpolationSearchWith = arraySearchInterpolation.interpolationSearchWith
module.exports.search.interpolationSearchLeftWith = arraySearchInterpolation.interpolationSearchLeftWith
module.exports.search.interpolationSearchRightWith = arraySearchInterpolation.interpolationSearchRightWith
module.exports.search.interpolationSearchBy = arraySearchInterpolation.interpolationSearchBy
module.exports.search.interpolationSearchLeftBy = arraySearchInterpolation.interpolationSearchLeftBy
module.exports.search.interpolationSearchRightBy = arraySearchInterpolation.interpolationSearchRightBy
module.exports.search.interpolationSearchByPure = arraySearchInterpolation.interpolationSearchByPure
module.exports.search.interpolationSearchLeftByPure = arraySearchInterpolation.interpolationSearchLeftByPure
module.exports.search.interpolationSearchRightByPure = arraySearchInterpolation.interpolationSearchRightByPure
module.exports.search.interpolationSearch = arraySearchInterpolation.interpolationSearch
module.exports.search.interpolationSearchLeft = arraySearchInterpolation.interpolationSearchLeft
module.exports.search.interpolationSearchRight = arraySearchInterpolation.interpolationSearchRight

const arraySearchLinear = require('./array/search/linear.js')
module.exports.search.__linearSearch = arraySearchLinear.__linearSearch
module.exports.search.__linearSearchRight = arraySearchLinear.__linearSearchRight

const arraySlice = require('./array/slice.js')
module.exports.slice = arraySlice.slice

const arraySome = require('./array/some.js')
module.exports.__some = arraySome.__some
module.exports.some = arraySome.some

const arraySort = require('./array/sort.js')
module.exports.__sort = arraySort.__sort
module.exports.sortWith = arraySort.sortWith
module.exports.sortBy = arraySort.sortBy
module.exports.sortByPure = arraySort.sortByPure
module.exports.sort = arraySort.sort

const arraySortingBinsertionsort = require('./array/sorting/binsertionsort.js')
module.exports.__binsertionsort = arraySortingBinsertionsort.__binsertionsort
module.exports.binsertionsortWith = arraySortingBinsertionsort.binsertionsortWith
module.exports.binsertionsortBy = arraySortingBinsertionsort.binsertionsortBy
module.exports.binsertionsortByPure = arraySortingBinsertionsort.binsertionsortByPure
module.exports.binsertionsort = arraySortingBinsertionsort.binsertionsort

const arraySortingHeapsort = require('./array/sorting/heapsort.js')
module.exports.__heapsort = arraySortingHeapsort.__heapsort
module.exports.heapsortWith = arraySortingHeapsort.heapsortWith
module.exports.heapsortBy = arraySortingHeapsort.heapsortBy
module.exports.heapsortByPure = arraySortingHeapsort.heapsortByPure
module.exports.heapsort = arraySortingHeapsort.heapsort

const arraySortingInsertionsort = require('./array/sorting/insertionsort.js')
module.exports.__insertionsort = arraySortingInsertionsort.__insertionsort
module.exports.insertionsortWith = arraySortingInsertionsort.insertionsortWith
module.exports.insertionsortBy = arraySortingInsertionsort.insertionsortBy
module.exports.insertionsortByPure = arraySortingInsertionsort.insertionsortByPure
module.exports.insertionsort = arraySortingInsertionsort.insertionsort

const arraySortingIntrosort = require('./array/sorting/introsort.js')
module.exports.__introsort = arraySortingIntrosort.__introsort
module.exports.introsortWith = arraySortingIntrosort.introsortWith
module.exports.introsortBy = arraySortingIntrosort.introsortBy
module.exports.introsortByPure = arraySortingIntrosort.introsortByPure
module.exports.introsort = arraySortingIntrosort.introsort

const arraySortingMergesort = require('./array/sorting/mergesort.js')
module.exports.__mergesort = arraySortingMergesort.__mergesort
module.exports.mergesortWith = arraySortingMergesort.mergesortWith
module.exports.mergesortBy = arraySortingMergesort.mergesortBy
module.exports.mergesortByPure = arraySortingMergesort.mergesortByPure
module.exports.mergesort = arraySortingMergesort.mergesort

const arraySortingQuicksortPartitionByHoare = require('./array/sorting/quicksort/partition-by-hoare.js')
module.exports.__partitionByHoare = arraySortingQuicksortPartitionByHoare.__partitionByHoare

const arraySortingQuicksortPartitionByLomuto = require('./array/sorting/quicksort/partition-by-lomuto.js')
module.exports.__partitionByLomuto = arraySortingQuicksortPartitionByLomuto.__partitionByLomuto

const arraySortingQuicksortPartitionLeftRight = require('./array/sorting/quicksort/partition-left-right.js')
module.exports.__partitionLeftRight = arraySortingQuicksortPartitionLeftRight.__partitionLeftRight

const arraySortingQuicksortSelectPivotLast = require('./array/sorting/quicksort/select-pivot-last.js')
module.exports.__selectPivotLast = arraySortingQuicksortSelectPivotLast.__selectPivotLast

const arraySortingQuicksortSelectPivotMedianOfThree = require('./array/sorting/quicksort/select-pivot-median-of-three.js')
module.exports.__selectPivotMedianOfThree = arraySortingQuicksortSelectPivotMedianOfThree.__selectPivotMedianOfThree

const arraySortingShellsort = require('./array/sorting/shellsort.js')
module.exports.__shellsort = arraySortingShellsort.__shellsort
module.exports.shellsortWith = arraySortingShellsort.shellsortWith
module.exports.shellsortBy = arraySortingShellsort.shellsortBy
module.exports.shellsortByPure = arraySortingShellsort.shellsortByPure
module.exports.shellsort = arraySortingShellsort.shellsort

const arraySortingTimsort = require('./array/sorting/timsort.js')
module.exports.__timsort = arraySortingTimsort.__timsort
module.exports.timsortWith = arraySortingTimsort.timsortWith
module.exports.timsortBy = arraySortingTimsort.timsortBy
module.exports.timsortByPure = arraySortingTimsort.timsortByPure
module.exports.timsort = arraySortingTimsort.timsort

const arraySplit = require('./array/split.js')
module.exports.array.__split = arraySplit.__split
module.exports.array.splitWith = arraySplit.splitWith
module.exports.array.splitBy = arraySplit.splitBy
module.exports.array.split = arraySplit.split

const arrayStartIndex = require('./array/start-index.js')
module.exports.startIndex = arrayStartIndex.startIndex

const arraySum = require('./array/sum.js')
module.exports.sumBy = arraySum.sumBy
module.exports.sum = arraySum.sum

const arraySwap = require('./array/swap.js')
module.exports.__swap = arraySwap.__swap
module.exports.swap = arraySwap.swap

const arrayTreeBinary = require('./array/tree/binary.js')
module.exports.tree.binary.getParent = arrayTreeBinary.getParent
module.exports.tree.binary.getLeft = arrayTreeBinary.getLeft
module.exports.tree.binary.getRight = arrayTreeBinary.getRight

const arrayTreeOctonary = require('./array/tree/octonary.js')
module.exports.tree.octonary.getParent = arrayTreeOctonary.getParent
module.exports.tree.octonary.getFrontTopLeft = arrayTreeOctonary.getFrontTopLeft
module.exports.tree.octonary.getFrontTopRight = arrayTreeOctonary.getFrontTopRight
module.exports.tree.octonary.getFrontBottomLeft = arrayTreeOctonary.getFrontBottomLeft
module.exports.tree.octonary.getFrontBottomRight = arrayTreeOctonary.getFrontBottomRight
module.exports.tree.octonary.getBackTopLeft = arrayTreeOctonary.getBackTopLeft
module.exports.tree.octonary.getBackTopRight = arrayTreeOctonary.getBackTopRight
module.exports.tree.octonary.getBackBottomLeft = arrayTreeOctonary.getBackBottomLeft
module.exports.tree.octonary.getBackBottomRight = arrayTreeOctonary.getBackBottomRight

const arrayTreeQuaternary = require('./array/tree/quaternary.js')
module.exports.tree.quaternary.getParent = arrayTreeQuaternary.getParent
module.exports.tree.quaternary.getTopLeft = arrayTreeQuaternary.getTopLeft
module.exports.tree.quaternary.getTopRight = arrayTreeQuaternary.getTopRight
module.exports.tree.quaternary.getBottomLeft = arrayTreeQuaternary.getBottomLeft
module.exports.tree.quaternary.getBottomRight = arrayTreeQuaternary.getBottomRight

const arrayUniq = require('./array/uniq.js')
module.exports.__uniq = arrayUniq.__uniq
module.exports.uniqWith = arrayUniq.uniqWith
module.exports.uniqBy = arrayUniq.uniqBy
module.exports.uniqByPure = arrayUniq.uniqByPure
module.exports.uniq = arrayUniq.uniq
module.exports.uniqWithSorted = arrayUniq.uniqWithSorted
module.exports.uniqBySorted = arrayUniq.uniqBySorted
module.exports.uniqByPureSorted = arrayUniq.uniqByPureSorted
module.exports.uniqSorted = arrayUniq.uniqSorted

const arrayUnweave = require('./array/unweave.js')
module.exports.unweave = arrayUnweave.unweave

const arrayWeave = require('./array/weave.js')
module.exports.weaveTwo = arrayWeave.weaveTwo
module.exports.weave = arrayWeave.weave

const arrayXor = require('./array/xor.js')
module.exports.__xor = arrayXor.__xor
module.exports.__xorSorted = arrayXor.__xorSorted
module.exports.xorWith = arrayXor.xorWith
module.exports.xorBy = arrayXor.xorBy
module.exports.xorByPure = arrayXor.xorByPure
module.exports.xor = arrayXor.xor
module.exports.xorWithSorted = arrayXor.xorWithSorted
module.exports.xorBySorted = arrayXor.xorBySorted
module.exports.xorByPureSorted = arrayXor.xorByPureSorted
module.exports.xorSorted = arrayXor.xorSorted

const arrayZip = require('./array/zip.js')
module.exports.__zip = arrayZip.__zip
module.exports.zipWith = arrayZip.zipWith
module.exports.zip = arrayZip.zip

const functionArityBinary = require('./function/arity/binary.js')
module.exports.binary = functionArityBinary.binary

const functionArityNAry = require('./function/arity/n-ary.js')
module.exports.nAry = functionArityNAry.nAry

const functionArityNullary = require('./function/arity/nullary.js')
module.exports.nullary = functionArityNullary.nullary

const functionArityTernary = require('./function/arity/ternary.js')
module.exports.ternary = functionArityTernary.ternary

const functionArityUnary = require('./function/arity/unary.js')
module.exports.unary = functionArityUnary.unary

const functionAsyncAfter = require('./function/async/after.js')
module.exports.after = functionAsyncAfter.after

const functionAsyncAmrap = require('./function/async/amrap.js')
module.exports.amrap = functionAsyncAmrap.amrap

const functionAsyncBefore = require('./function/async/before.js')
module.exports.before = functionAsyncBefore.before

const functionAsyncDebounce = require('./function/async/debounce.js')
module.exports.debounce = functionAsyncDebounce.debounce

const functionAsyncDelay = require('./function/async/delay.js')
module.exports.delay = functionAsyncDelay.delay

const functionAsyncOnce = require('./function/async/once.js')
module.exports.once = functionAsyncOnce.once

const functionAsyncThrottle = require('./function/async/throttle.js')
module.exports.throttle = functionAsyncThrottle.throttle

const functionAsyncTime = require('./function/async/time.js')
module.exports.time = functionAsyncTime.time

const functionCompare = require('./function/compare.js')
module.exports.compare = functionCompare.compare

const functionIdentity = require('./function/identity.js')
module.exports.identity = functionIdentity.identity

const functionMemoize = require('./function/memoize.js')
module.exports.memoize = functionMemoize.memoize

const functionMiddleware = require('./function/middleware.js')
module.exports.makeMiddleware = functionMiddleware.makeMiddleware

const functionNoop = require('./function/noop.js')
module.exports.noop = functionNoop.noop

const functionPass = require('./function/pass.js')
module.exports.pass = functionPass.pass

const functionPipe = require('./function/pipe.js')
module.exports.pipe = functionPipe.pipe

const ieeeFloatDouble = require('./ieee-float/double.js')
module.exports.ieeeFloat.double.EXPONENT_BITS = ieeeFloatDouble.EXPONENT_BITS
module.exports.ieeeFloat.double.MANTISSA_BITS = ieeeFloatDouble.MANTISSA_BITS
module.exports.ieeeFloat.double.EXPONENT_BIAS = ieeeFloatDouble.EXPONENT_BIAS
module.exports.ieeeFloat.double.HIDDEN_BIT = ieeeFloatDouble.HIDDEN_BIT
module.exports.ieeeFloat.double.sign = ieeeFloatDouble.sign
module.exports.ieeeFloat.double.exponent = ieeeFloatDouble.exponent
module.exports.ieeeFloat.double.mantissa = ieeeFloatDouble.mantissa
module.exports.ieeeFloat.double.parse = ieeeFloatDouble.parse
module.exports.ieeeFloat.double.from = ieeeFloatDouble.from
module.exports.ieeeFloat.double.nextToward = ieeeFloatDouble.nextToward

const ieeeFloatSingle = require('./ieee-float/single.js')
module.exports.ieeeFloat.single.EXPONENT_BITS = ieeeFloatSingle.EXPONENT_BITS
module.exports.ieeeFloat.single.MANTISSA_BITS = ieeeFloatSingle.MANTISSA_BITS
module.exports.ieeeFloat.single.EXPONENT_BIAS = ieeeFloatSingle.EXPONENT_BIAS
module.exports.ieeeFloat.single.HIDDEN_BIT = ieeeFloatSingle.HIDDEN_BIT
module.exports.ieeeFloat.single.sign = ieeeFloatSingle.sign
module.exports.ieeeFloat.single.exponent = ieeeFloatSingle.exponent
module.exports.ieeeFloat.single.mantissa = ieeeFloatSingle.mantissa
module.exports.ieeeFloat.single.parse = ieeeFloatSingle.parse
module.exports.ieeeFloat.single.from = ieeeFloatSingle.from
module.exports.ieeeFloat.single.nextToward = ieeeFloatSingle.nextToward

const mapAddDefault = require('./map/add-default.js')
module.exports.addDefault = mapAddDefault.addDefault

const numberClamp = require('./number/clamp.js')
module.exports.clamp = numberClamp.clamp

const numberInterpolate = require('./number/interpolate.js')
module.exports.interpolate = numberInterpolate.interpolate

const numberModular = require('./number/modular.js')
module.exports.modular.add = numberModular.add
module.exports.modular.sub = numberModular.sub
module.exports.modular.inc = numberModular.inc
module.exports.modular.dec = numberModular.dec

const numberRounding = require('./number/rounding.js')
module.exports.floorTo = numberRounding.floorTo
module.exports.ceilTo = numberRounding.ceilTo
module.exports.roundTo = numberRounding.roundTo

const numberStringifyToExponential = require('./number/stringify/to-exponential.js')
module.exports.toExponential = numberStringifyToExponential.toExponential

const numberStringifyToFixed = require('./number/stringify/to-fixed.js')
module.exports.toFixed = numberStringifyToFixed.toFixed

const numberStringifyToLocaleString = require('./number/stringify/to-locale-string.js')
module.exports.toLocaleString = numberStringifyToLocaleString.toLocaleString

const numberStringifyToPrecision = require('./number/stringify/to-precision.js')
module.exports.toPrecision = numberStringifyToPrecision.toPrecision

const objectAccessors = require('./object/accessors.js')
module.exports._get = objectAccessors._get
module.exports.get = objectAccessors.get
module.exports._set = objectAccessors._set
module.exports.set = objectAccessors.set

const objectClone = require('./object/clone.js')
module.exports.object.clone = objectClone.clone

const objectDefaults = require('./object/defaults.js')
module.exports.defaults = objectDefaults.defaults

const objectExtend = require('./object/extend.js')
module.exports.extend = objectExtend.extend

const objectFromEntries = require('./object/from-entries.js')
module.exports.fromEntries = objectFromEntries.fromEntries

const objectIsEqual = require('./object/is-equal.js')
module.exports.isEqualWith = objectIsEqual.isEqualWith
module.exports.isEqual = objectIsEqual.isEqual

const objectKeys = require('./object/keys.js')
module.exports.keys = objectKeys.keys

const objectMapEntries = require('./object/map-entries.js')
module.exports.__mapEntries = objectMapEntries.__mapEntries
module.exports.mapEntries = objectMapEntries.mapEntries

const objectMapKeys = require('./object/map-keys.js')
module.exports.mapKeys = objectMapKeys.mapKeys

const objectMapValues = require('./object/map-values.js')
module.exports.mapValues = objectMapValues.mapValues

const objectMatches = require('./object/matches.js')
module.exports.matchesWith = objectMatches.matchesWith
module.exports.matches = objectMatches.matches

const objectMerge = require('./object/merge.js')
module.exports.object.__merge = objectMerge.__merge
module.exports.object.merge = objectMerge.merge

const objectPick = require('./object/pick.js')
module.exports.pick = objectPick.pick
module.exports.omit = objectPick.omit

const objectToEntries = require('./object/to-entries.js')
module.exports.toEntries = objectToEntries.toEntries

const objectValues = require('./object/values.js')
module.exports.values = objectValues.values

const objectZip = require('./object/zip.js')
module.exports.object.zip = objectZip.zip

const operatorsArithmeticAdd = require('./operators/arithmetic/add.js')
module.exports.add = operatorsArithmeticAdd.add

const operatorsArithmeticDiv = require('./operators/arithmetic/div.js')
module.exports.div = operatorsArithmeticDiv.div

const operatorsArithmeticMod = require('./operators/arithmetic/mod.js')
module.exports.mod = operatorsArithmeticMod.mod

const operatorsArithmeticMul = require('./operators/arithmetic/mul.js')
module.exports.mul = operatorsArithmeticMul.mul

const operatorsArithmeticNeg = require('./operators/arithmetic/neg.js')
module.exports.neg = operatorsArithmeticNeg.neg

const operatorsArithmeticPow = require('./operators/arithmetic/pow.js')
module.exports.pow = operatorsArithmeticPow.pow

const operatorsArithmeticSub = require('./operators/arithmetic/sub.js')
module.exports.sub = operatorsArithmeticSub.sub

const operatorsBitwiseBitAnd = require('./operators/bitwise/bit-and.js')
module.exports.bitAnd = operatorsBitwiseBitAnd.bitAnd

const operatorsBitwiseBitNot = require('./operators/bitwise/bit-not.js')
module.exports.bitNot = operatorsBitwiseBitNot.bitNot

const operatorsBitwiseBitOr = require('./operators/bitwise/bit-or.js')
module.exports.bitOr = operatorsBitwiseBitOr.bitOr

const operatorsBitwiseBitXor = require('./operators/bitwise/bit-xor.js')
module.exports.bitXor = operatorsBitwiseBitXor.bitXor

const operatorsBitwiseShiftL = require('./operators/bitwise/shift-l.js')
module.exports.shiftL = operatorsBitwiseShiftL.shiftL

const operatorsBitwiseShiftR = require('./operators/bitwise/shift-r.js')
module.exports.shiftR = operatorsBitwiseShiftR.shiftR

const operatorsBitwiseShiftZ = require('./operators/bitwise/shift-z.js')
module.exports.shiftZ = operatorsBitwiseShiftZ.shiftZ

const operatorsComparisonEq = require('./operators/comparison/eq.js')
module.exports.eq = operatorsComparisonEq.eq

const operatorsComparisonGt = require('./operators/comparison/gt.js')
module.exports.gt = operatorsComparisonGt.gt

const operatorsComparisonGte = require('./operators/comparison/gte.js')
module.exports.gte = operatorsComparisonGte.gte

const operatorsComparisonLt = require('./operators/comparison/lt.js')
module.exports.lt = operatorsComparisonLt.lt

const operatorsComparisonLte = require('./operators/comparison/lte.js')
module.exports.lte = operatorsComparisonLte.lte

const operatorsComparisonNeq = require('./operators/comparison/neq.js')
module.exports.neq = operatorsComparisonNeq.neq

const operatorsLogicalAnd = require('./operators/logical/and.js')
module.exports.and = operatorsLogicalAnd.and

const operatorsLogicalNil = require('./operators/logical/nil.js')
module.exports.nil = operatorsLogicalNil.nil

const operatorsLogicalNot = require('./operators/logical/not.js')
module.exports.not = operatorsLogicalNot.not

const operatorsLogicalOr = require('./operators/logical/or.js')
module.exports.or = operatorsLogicalOr.or

const promiseAllSettled = require('./promise/all-settled.js')
module.exports.allSettled = promiseAllSettled.allSettled

const promiseAll = require('./promise/all.js')
module.exports.all = promiseAll.all

const promiseCatch = require('./promise/catch.js')
module.exports.catch = promiseCatch.catch

const promiseFinally = require('./promise/finally.js')
module.exports.finally = promiseFinally.finally

const promiseRace = require('./promise/race.js')
module.exports.race = promiseRace.race

const promiseReject = require('./promise/reject.js')
module.exports.reject = promiseReject.reject

const promiseResolve = require('./promise/resolve.js')
module.exports.resolve = promiseResolve.resolve

const promiseSleep = require('./promise/sleep.js')
module.exports.sleep = promiseSleep.sleep

const promiseThen = require('./promise/then.js')
module.exports.then = promiseThen.then

const promiseTimeout = require('./promise/timeout.js')
module.exports.timeout = promiseTimeout.timeout

const randomChooseN = require('./random/choose-n.js')
module.exports.__chooseN = randomChooseN.__chooseN
module.exports.chooseN = randomChooseN.chooseN

const randomChoose = require('./random/choose.js')
module.exports.choose = randomChoose.choose

const randomRandFloat = require('./random/rand-float.js')
module.exports.randFloat = randomRandFloat.randFloat

const randomRandInt = require('./random/rand-int.js')
module.exports.randInt = randomRandInt.randInt

const randomRand = require('./random/rand.js')
module.exports.rand = randomRand.rand

const randomRandom = require('./random/random.js')
module.exports.random = randomRandom.random

const randomSeededMiddleSquareWeyl = require('./random/seeded/middle-square-weyl.js')
module.exports.MiddleSquareWeyl = randomSeededMiddleSquareWeyl.MiddleSquareWeyl

const randomShuffle = require('./random/shuffle.js')
module.exports.__shuffle = randomShuffle.__shuffle
module.exports.shuffle = randomShuffle.shuffle

const rangeRange = require('./range/range.js')
module.exports.range = rangeRange.range

const rangeXrange = require('./range/xrange.js')
module.exports.xrange = rangeXrange.xrange

const setDifference = require('./set/difference.js')
module.exports.sets.difference = setDifference.difference

const setIntersection = require('./set/intersection.js')
module.exports.sets.intersection = setIntersection.intersection

const setUnion = require('./set/union.js')
module.exports.sets.union = setUnion.union

const setXor = require('./set/xor.js')
module.exports.sets.xor = setXor.xor

const stringCaseCamel = require('./string/case/camel.js')
module.exports.camelCase = stringCaseCamel.camelCase
module.exports.isCamelCase = stringCaseCamel.isCamelCase

const stringCaseCapitalize = require('./string/case/capitalize.js')
module.exports.capitalize = stringCaseCapitalize.capitalize
module.exports.isCapitalized = stringCaseCapitalize.isCapitalized

const stringCaseKebab = require('./string/case/kebab.js')
module.exports.kebabCase = stringCaseKebab.kebabCase
module.exports.isKebabCase = stringCaseKebab.isKebabCase

const stringCaseLocaleLower = require('./string/case/locale-lower.js')
module.exports.localeLowerCase = stringCaseLocaleLower.localeLowerCase
module.exports.isLocaleLowerCase = stringCaseLocaleLower.isLocaleLowerCase

const stringCaseLocaleUpper = require('./string/case/locale-upper.js')
module.exports.localeUpperCase = stringCaseLocaleUpper.localeUpperCase
module.exports.isLocaleUpperCase = stringCaseLocaleUpper.isLocaleUpperCase

const stringCaseLower = require('./string/case/lower.js')
module.exports.lowerCase = stringCaseLower.lowerCase
module.exports.isLowerCase = stringCaseLower.isLowerCase

const stringCasePascal = require('./string/case/pascal.js')
module.exports.pascalCase = stringCasePascal.pascalCase
module.exports.isPascalCase = stringCasePascal.isPascalCase

const stringCaseSnake = require('./string/case/snake.js')
module.exports.snakeCase = stringCaseSnake.snakeCase
module.exports.isSnakeCase = stringCaseSnake.isSnakeCase

const stringCaseUpperFirst = require('./string/case/upper-first.js')
module.exports.upperFirst = stringCaseUpperFirst.upperFirst
module.exports.isUpperFirst = stringCaseUpperFirst.isUpperFirst

const stringCaseUpper = require('./string/case/upper.js')
module.exports.upperCase = stringCaseUpper.upperCase
module.exports.isUpperCase = stringCaseUpper.isUpperCase

const stringCharAt = require('./string/char-at.js')
module.exports.charAt = stringCharAt.charAt
module.exports.charCodeAt = stringCharAt.charCodeAt
module.exports.charPointAt = stringCharAt.charPointAt

const stringEndsWith = require('./string/ends-with.js')
module.exports.endsWith = stringEndsWith.endsWith

const stringJoin = require('./string/join.js')
module.exports.join = stringJoin.join

const stringLocaleCompare = require('./string/locale-compare.js')
module.exports.localeCompare = stringLocaleCompare.localeCompare

const stringMatch = require('./string/match.js')
module.exports.match = stringMatch.match
module.exports.matchAll = stringMatch.matchAll
module.exports.search = stringMatch.search

const stringNormalize = require('./string/normalize.js')
module.exports.normalize = stringNormalize.normalize

const stringPad = require('./string/pad.js')
module.exports.padStart = stringPad.padStart
module.exports.padEnd = stringPad.padEnd

const stringRepeat = require('./string/repeat.js')
module.exports.repeat = stringRepeat.repeat

const stringReplace = require('./string/replace.js')
module.exports.replace = stringReplace.replace

const stringSplit = require('./string/split.js')
module.exports.split = stringSplit.split

const stringStartsWith = require('./string/starts-with.js')
module.exports.startsWith = stringStartsWith.startsWith

const stringSubstring = require('./string/substring.js')
module.exports.substring = stringSubstring.substring

const stringTrim = require('./string/trim.js')
module.exports.trim = stringTrim.trim
module.exports.trimEnd = stringTrim.trimEnd
module.exports.trimStart = stringTrim.trimStart

